@startuml
'https://plantuml.com/class-diagram

skinparam component {
    backgroundcolor<<Choreographer>> #cdcdcd
    stereotypefontsize 8
}

component "Client" as client

component "App Shell" as appShell {
    component "Choreographer" <<Choreographer>> as messageBroker
    component "Templates" as templates
    component "Navigation" as navigation

    component "BC  A- Micro UI"  as microUiA
    component "BC B - Micro UI"  as microUiB
}

component "Server" {
    component "Bounded Context A" as bcA
    component "Bounded Context B" as bcB
}

client --> appShell

microUiA -down-> bcA
microUiB -down-> bcB

microUiA -up-> messageBroker
microUiB -up-> messageBroker

' Layout
templates -down[hidden]-> navigation


@enduml