@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Team member A" as teamMemberA
actor "Team member B" as teamMemberB

participant "Task Management\nUser Interface" as taskMmgtUi
participant "App Shell\nChoreographer" as appShell
participant "Header" as headerUi
participant "Task Management\nBounded Context" as taskMmgtBc

appShell --> taskMmgtBc : Register to WebHook URL

group "Task Creation"
    teamMemberA --> taskMmgtUi: Create task
    taskMmgtUi --> taskMmgtBc: Create task
    taskMmgtBc --> appShell : Produce event \n"Task created"
    headerUi --> appShell : Consume event \n"Task created"
    headerUi --> headerUi : Update number\nof open tasks
end group

group "Task Assignment"
    teamMemberB --> taskMmgtUi: Assign task\nto team member A
    taskMmgtUi --> taskMmgtBc: Assign task\nto team member A
    taskMmgtBc --> appShell: Produce event \n"Task assigned"
    headerUi --> appShell: Consume event \n""Task assigned"
    headerUi --> headerUi: Update number\nof assigned tasks
    headerUi --> headerUi : Update number\nof open tasks
end task



@enduml